name: "📋 Task"
description: "Use this template to create a new lab task."
labels:
  - task
body:
  - type: markdown
    attributes:
      value: |
        <!--
        Briefly describe:
        1) What needs to be done
        2) Why it’s needed
        3) Any context or links
        -->
  - type: input
    id: task-title
    attributes:
      label: "Task title"
      description: "Short title for this issue"
      placeholder: "e.g., Style meeting minutes header"
    validations:
      required: true
  - type: textarea
    id: task-details
    attributes:
      label: "Task details"
      description: "More detailed description of work"
    validations:
      required: true
  - type: checkboxes
    id: confirm-instructions
    attributes:
      label: "Checklist"
      description: "Confirm before filing"
      options:
        - label: "I have read the lab instructions and this task corresponds to one checklist item"
    validations:
      required: true
