name: 📋 Task
description: Use this template to create a new lab task.
labels: task
body:
  - type: markdown
    attributes:
      value: |
        <!--
        Briefly describe:
        1) What needs to be done
        2) Why it’s needed
        3) Any context or links
        -->
  - type: boolean
    attributes:
      label: I have read the lab instructions and this task corresponds to one checklist item.
      default: false
